"""updated users table

Revision ID: b9bb8d7d728b
Revises: bcb6a7efc75b
Create Date: 2023-01-16 02:59:44.240684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9bb8d7d728b'
down_revision = 'bcb6a7efc75b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(), server_default=sa.text('1'), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
